### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ArcticSpaceFox** [melsman/aplparse#4]
sry a noob, but installing via smackage always tells me
`ERROR: No acceptable version of 'aplparse' around, try getting one with 'smackage get'?`

Here is my Dockerfile for setting it up
```Dockerfile
FROM ubuntu:latest

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y curl \
    ca-certificates \
    clang \
    build-essential \
    g++ \
    git \
    make

RUN git clone https://github.com/melsman/unicode

#RUN git clone https://github.com/MLton/mlton && cd mlton
#RUN make all && make install && cd
RUN apt-get install -y mlton

RUN git clone https://github.com/standardml/smackage
RUN cd smackage && make mlton
RUN cp /smackage/bin/smackage /bin/

RUN cd && rm -rf smackage

RUN mkdir .smackage && touch .smackage/sources.list && echo "aplparse git git://github.com/melsman/aplparse.git" >> .smackage/sources.list
RUN smackage refresh
RUN git clone https://github.com/melsman/aplparse && cd aplparse
RUN smackage make aplparse clean && smackage make aplparse tests

RUN git clone https://github.com/melsman/aplcompile && cd aplcompile
RUN make aplc && ./aplc
```

**Comment by ArcticSpaceFox** [comment]
I also tried getting it via `smackage get`, but the it tells me that there was nothin found

**Comment by melsman** [comment]
I have moved the development of the unicode and aplparse sources to
github.com/diku-dk/sml-unicode and github.com/diku-dk/sml-aplparse,
respectively, and migrated to make use of smlpkg instead of smackage, which
makes the whole handling of packages so much easier; see the changes to
github.com/melsman/apltail...

Best,

Martin

man. 11. jan. 2021 kl. 15.00 skrev ArcitcSpaceFox <notifications@github.com

**Comment by ArcticSpaceFox** [comment]
Thanks :)
